require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpellsController do

  # This should return the minimal set of attributes required to create a valid
  # Spell. As you add validations to Spell, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "hero" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpellsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all spells as @spells" do
      spell = Spell.create! valid_attributes
      get :index, {}, valid_session
      assigns(:spells).should eq([spell])
    end
  end

  describe "GET show" do
    it "assigns the requested spell as @spell" do
      spell = Spell.create! valid_attributes
      get :show, {:id => spell.to_param}, valid_session
      assigns(:spell).should eq(spell)
    end
  end

  describe "GET new" do
    it "assigns a new spell as @spell" do
      get :new, {}, valid_session
      assigns(:spell).should be_a_new(Spell)
    end
  end

  describe "GET edit" do
    it "assigns the requested spell as @spell" do
      spell = Spell.create! valid_attributes
      get :edit, {:id => spell.to_param}, valid_session
      assigns(:spell).should eq(spell)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Spell" do
        expect {
          post :create, {:spell => valid_attributes}, valid_session
        }.to change(Spell, :count).by(1)
      end

      it "assigns a newly created spell as @spell" do
        post :create, {:spell => valid_attributes}, valid_session
        assigns(:spell).should be_a(Spell)
        assigns(:spell).should be_persisted
      end

      it "redirects to the created spell" do
        post :create, {:spell => valid_attributes}, valid_session
        response.should redirect_to(Spell.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spell as @spell" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spell.any_instance.stub(:save).and_return(false)
        post :create, {:spell => { "hero" => "invalid value" }}, valid_session
        assigns(:spell).should be_a_new(Spell)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spell.any_instance.stub(:save).and_return(false)
        post :create, {:spell => { "hero" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spell" do
        spell = Spell.create! valid_attributes
        # Assuming there are no other spells in the database, this
        # specifies that the Spell created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Spell.any_instance.should_receive(:update).with({ "hero" => "" })
        put :update, {:id => spell.to_param, :spell => { "hero" => "" }}, valid_session
      end

      it "assigns the requested spell as @spell" do
        spell = Spell.create! valid_attributes
        put :update, {:id => spell.to_param, :spell => valid_attributes}, valid_session
        assigns(:spell).should eq(spell)
      end

      it "redirects to the spell" do
        spell = Spell.create! valid_attributes
        put :update, {:id => spell.to_param, :spell => valid_attributes}, valid_session
        response.should redirect_to(spell)
      end
    end

    describe "with invalid params" do
      it "assigns the spell as @spell" do
        spell = Spell.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spell.any_instance.stub(:save).and_return(false)
        put :update, {:id => spell.to_param, :spell => { "hero" => "invalid value" }}, valid_session
        assigns(:spell).should eq(spell)
      end

      it "re-renders the 'edit' template" do
        spell = Spell.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spell.any_instance.stub(:save).and_return(false)
        put :update, {:id => spell.to_param, :spell => { "hero" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spell" do
      spell = Spell.create! valid_attributes
      expect {
        delete :destroy, {:id => spell.to_param}, valid_session
      }.to change(Spell, :count).by(-1)
    end

    it "redirects to the spells list" do
      spell = Spell.create! valid_attributes
      delete :destroy, {:id => spell.to_param}, valid_session
      response.should redirect_to(spells_url)
    end
  end

end
